export interface RoadmapProblem {
  title: string;
  slug: string;
  difficulty: "Easy" | "Medium" | "Hard";
}

export interface RoadmapGroup {
  title: string;
  problems: RoadmapProblem[];
}

export interface Roadmap {
  id: string;
  name: string;
  shortName: string;
  description: string;
  totalProblems: number;
  groups: RoadmapGroup[];
}

export const ROADMAPS: Roadmap[] = [
  {
    id: "neetcode-150",
    name: "NeetCode 150",
    shortName: "NC 150",
    description:
      "The definitive list of 150 LeetCode problems curated by NeetCode, covering every major pattern needed to ace technical interviews at top companies.",
    totalProblems: 150,
    groups: [
      {
        title: "Arrays & Hashing",
        problems: [
          { title: "Contains Duplicate", slug: "contains-duplicate", difficulty: "Easy" },
          { title: "Valid Anagram", slug: "valid-anagram", difficulty: "Easy" },
          { title: "Two Sum", slug: "two-sum", difficulty: "Easy" },
          { title: "Group Anagrams", slug: "group-anagrams", difficulty: "Medium" },
          { title: "Top K Frequent Elements", slug: "top-k-frequent-elements", difficulty: "Medium" },
          { title: "Encode and Decode Strings", slug: "encode-and-decode-strings", difficulty: "Medium" },
          { title: "Product of Array Except Self", slug: "product-of-array-except-self", difficulty: "Medium" },
          { title: "Valid Sudoku", slug: "valid-sudoku", difficulty: "Medium" },
          { title: "Longest Consecutive Sequence", slug: "longest-consecutive-sequence", difficulty: "Medium" },
        ],
      },
      {
        title: "Two Pointers",
        problems: [
          { title: "Valid Palindrome", slug: "valid-palindrome", difficulty: "Easy" },
          { title: "Two Sum II - Input Array Is Sorted", slug: "two-sum-ii-input-array-is-sorted", difficulty: "Medium" },
          { title: "3Sum", slug: "3sum", difficulty: "Medium" },
          { title: "Container With Most Water", slug: "container-with-most-water", difficulty: "Medium" },
          { title: "Trapping Rain Water", slug: "trapping-rain-water", difficulty: "Hard" },
        ],
      },
      {
        title: "Sliding Window",
        problems: [
          { title: "Best Time to Buy and Sell Stock", slug: "best-time-to-buy-and-sell-stock", difficulty: "Easy" },
          { title: "Longest Substring Without Repeating Characters", slug: "longest-substring-without-repeating-characters", difficulty: "Medium" },
          { title: "Longest Repeating Character Replacement", slug: "longest-repeating-character-replacement", difficulty: "Medium" },
          { title: "Permutation in String", slug: "permutation-in-string", difficulty: "Medium" },
          { title: "Minimum Window Substring", slug: "minimum-window-substring", difficulty: "Hard" },
          { title: "Sliding Window Maximum", slug: "sliding-window-maximum", difficulty: "Hard" },
        ],
      },
      {
        title: "Stack",
        problems: [
          { title: "Valid Parentheses", slug: "valid-parentheses", difficulty: "Easy" },
          { title: "Min Stack", slug: "min-stack", difficulty: "Medium" },
          { title: "Evaluate Reverse Polish Notation", slug: "evaluate-reverse-polish-notation", difficulty: "Medium" },
          { title: "Generate Parentheses", slug: "generate-parentheses", difficulty: "Medium" },
          { title: "Daily Temperatures", slug: "daily-temperatures", difficulty: "Medium" },
          { title: "Car Fleet", slug: "car-fleet", difficulty: "Medium" },
          { title: "Largest Rectangle in Histogram", slug: "largest-rectangle-in-histogram", difficulty: "Hard" },
        ],
      },
      {
        title: "Binary Search",
        problems: [
          { title: "Binary Search", slug: "binary-search", difficulty: "Easy" },
          { title: "Search a 2D Matrix", slug: "search-a-2d-matrix", difficulty: "Medium" },
          { title: "Koko Eating Bananas", slug: "koko-eating-bananas", difficulty: "Medium" },
          { title: "Find Minimum in Rotated Sorted Array", slug: "find-minimum-in-rotated-sorted-array", difficulty: "Medium" },
          { title: "Search in Rotated Sorted Array", slug: "search-in-rotated-sorted-array", difficulty: "Medium" },
          { title: "Time Based Key-Value Store", slug: "time-based-key-value-store", difficulty: "Medium" },
          { title: "Median of Two Sorted Arrays", slug: "median-of-two-sorted-arrays", difficulty: "Hard" },
        ],
      },
      {
        title: "Linked List",
        problems: [
          { title: "Reverse Linked List", slug: "reverse-linked-list", difficulty: "Easy" },
          { title: "Merge Two Sorted Lists", slug: "merge-two-sorted-lists", difficulty: "Easy" },
          { title: "Reorder List", slug: "reorder-list", difficulty: "Medium" },
          { title: "Remove Nth Node From End of List", slug: "remove-nth-node-from-end-of-list", difficulty: "Medium" },
          { title: "Copy List with Random Pointer", slug: "copy-list-with-random-pointer", difficulty: "Medium" },
          { title: "Add Two Numbers", slug: "add-two-numbers", difficulty: "Medium" },
          { title: "Linked List Cycle", slug: "linked-list-cycle", difficulty: "Easy" },
          { title: "Find the Duplicate Number", slug: "find-the-duplicate-number", difficulty: "Medium" },
          { title: "LRU Cache", slug: "lru-cache", difficulty: "Medium" },
          { title: "Merge K Sorted Lists", slug: "merge-k-sorted-lists", difficulty: "Hard" },
          { title: "Reverse Nodes in k-Group", slug: "reverse-nodes-in-k-group", difficulty: "Hard" },
        ],
      },
      {
        title: "Trees",
        problems: [
          { title: "Invert Binary Tree", slug: "invert-binary-tree", difficulty: "Easy" },
          { title: "Maximum Depth of Binary Tree", slug: "maximum-depth-of-binary-tree", difficulty: "Easy" },
          { title: "Diameter of Binary Tree", slug: "diameter-of-binary-tree", difficulty: "Easy" },
          { title: "Balanced Binary Tree", slug: "balanced-binary-tree", difficulty: "Easy" },
          { title: "Same Tree", slug: "same-tree", difficulty: "Easy" },
          { title: "Subtree of Another Tree", slug: "subtree-of-another-tree", difficulty: "Easy" },
          { title: "Lowest Common Ancestor of a BST", slug: "lowest-common-ancestor-of-a-binary-search-tree", difficulty: "Medium" },
          { title: "Binary Tree Level Order Traversal", slug: "binary-tree-level-order-traversal", difficulty: "Medium" },
          { title: "Binary Tree Right Side View", slug: "binary-tree-right-side-view", difficulty: "Medium" },
          { title: "Count Good Nodes in Binary Tree", slug: "count-good-nodes-in-binary-tree", difficulty: "Medium" },
          { title: "Validate Binary Search Tree", slug: "validate-binary-search-tree", difficulty: "Medium" },
          { title: "Kth Smallest Element in a BST", slug: "kth-smallest-element-in-a-bst", difficulty: "Medium" },
          { title: "Construct Binary Tree from Preorder and Inorder Traversal", slug: "construct-binary-tree-from-preorder-and-inorder-traversal", difficulty: "Medium" },
          { title: "Binary Tree Maximum Path Sum", slug: "binary-tree-maximum-path-sum", difficulty: "Hard" },
          { title: "Serialize and Deserialize Binary Tree", slug: "serialize-and-deserialize-binary-tree", difficulty: "Hard" },
        ],
      },
      {
        title: "Tries",
        problems: [
          { title: "Implement Trie (Prefix Tree)", slug: "implement-trie-prefix-tree", difficulty: "Medium" },
          { title: "Design Add and Search Words Data Structure", slug: "design-add-and-search-words-data-structure", difficulty: "Medium" },
          { title: "Word Search II", slug: "word-search-ii", difficulty: "Hard" },
        ],
      },
      {
        title: "Heap / Priority Queue",
        problems: [
          { title: "Kth Largest Element in a Stream", slug: "kth-largest-element-in-a-stream", difficulty: "Easy" },
          { title: "Last Stone Weight", slug: "last-stone-weight", difficulty: "Easy" },
          { title: "K Closest Points to Origin", slug: "k-closest-points-to-origin", difficulty: "Medium" },
          { title: "Kth Largest Element in an Array", slug: "kth-largest-element-in-an-array", difficulty: "Medium" },
          { title: "Task Scheduler", slug: "task-scheduler", difficulty: "Medium" },
          { title: "Design Twitter", slug: "design-twitter", difficulty: "Medium" },
          { title: "Find Median from Data Stream", slug: "find-median-from-data-stream", difficulty: "Hard" },
        ],
      },
      {
        title: "Backtracking",
        problems: [
          { title: "Subsets", slug: "subsets", difficulty: "Medium" },
          { title: "Combination Sum", slug: "combination-sum", difficulty: "Medium" },
          { title: "Permutations", slug: "permutations", difficulty: "Medium" },
          { title: "Subsets II", slug: "subsets-ii", difficulty: "Medium" },
          { title: "Combination Sum II", slug: "combination-sum-ii", difficulty: "Medium" },
          { title: "Word Search", slug: "word-search", difficulty: "Medium" },
          { title: "Palindrome Partitioning", slug: "palindrome-partitioning", difficulty: "Medium" },
          { title: "Letter Combinations of a Phone Number", slug: "letter-combinations-of-a-phone-number", difficulty: "Medium" },
          { title: "N-Queens", slug: "n-queens", difficulty: "Hard" },
        ],
      },
      {
        title: "Graphs",
        problems: [
          { title: "Number of Islands", slug: "number-of-islands", difficulty: "Medium" },
          { title: "Clone Graph", slug: "clone-graph", difficulty: "Medium" },
          { title: "Max Area of Island", slug: "max-area-of-island", difficulty: "Medium" },
          { title: "Pacific Atlantic Water Flow", slug: "pacific-atlantic-water-flow", difficulty: "Medium" },
          { title: "Surrounded Regions", slug: "surrounded-regions", difficulty: "Medium" },
          { title: "Rotting Oranges", slug: "rotting-oranges", difficulty: "Medium" },
          { title: "Walls and Gates", slug: "walls-and-gates", difficulty: "Medium" },
          { title: "Course Schedule", slug: "course-schedule", difficulty: "Medium" },
          { title: "Course Schedule II", slug: "course-schedule-ii", difficulty: "Medium" },
          { title: "Redundant Connection", slug: "redundant-connection", difficulty: "Medium" },
          { title: "Number of Connected Components in an Undirected Graph", slug: "number-of-connected-components-in-an-undirected-graph", difficulty: "Medium" },
          { title: "Graph Valid Tree", slug: "graph-valid-tree", difficulty: "Medium" },
          { title: "Word Ladder", slug: "word-ladder", difficulty: "Hard" },
        ],
      },
      {
        title: "Advanced Graphs",
        problems: [
          { title: "Reconstruct Itinerary", slug: "reconstruct-itinerary", difficulty: "Hard" },
          { title: "Min Cost to Connect All Points", slug: "min-cost-to-connect-all-points", difficulty: "Medium" },
          { title: "Network Delay Time", slug: "network-delay-time", difficulty: "Medium" },
          { title: "Swim in Rising Water", slug: "swim-in-rising-water", difficulty: "Hard" },
          { title: "Alien Dictionary", slug: "alien-dictionary", difficulty: "Hard" },
          { title: "Cheapest Flights Within K Stops", slug: "find-cheapest-flights-within-k-stops", difficulty: "Medium" },
        ],
      },
      {
        title: "1-D Dynamic Programming",
        problems: [
          { title: "Climbing Stairs", slug: "climbing-stairs", difficulty: "Easy" },
          { title: "Min Cost Climbing Stairs", slug: "min-cost-climbing-stairs", difficulty: "Easy" },
          { title: "House Robber", slug: "house-robber", difficulty: "Medium" },
          { title: "House Robber II", slug: "house-robber-ii", difficulty: "Medium" },
          { title: "Longest Palindromic Substring", slug: "longest-palindromic-substring", difficulty: "Medium" },
          { title: "Palindromic Substrings", slug: "palindromic-substrings", difficulty: "Medium" },
          { title: "Decode Ways", slug: "decode-ways", difficulty: "Medium" },
          { title: "Coin Change", slug: "coin-change", difficulty: "Medium" },
          { title: "Maximum Product Subarray", slug: "maximum-product-subarray", difficulty: "Medium" },
          { title: "Word Break", slug: "word-break", difficulty: "Medium" },
          { title: "Longest Increasing Subsequence", slug: "longest-increasing-subsequence", difficulty: "Medium" },
          { title: "Partition Equal Subset Sum", slug: "partition-equal-subset-sum", difficulty: "Medium" },
        ],
      },
      {
        title: "2-D Dynamic Programming",
        problems: [
          { title: "Unique Paths", slug: "unique-paths", difficulty: "Medium" },
          { title: "Longest Common Subsequence", slug: "longest-common-subsequence", difficulty: "Medium" },
          { title: "Best Time to Buy and Sell Stock with Cooldown", slug: "best-time-to-buy-and-sell-stock-with-cooldown", difficulty: "Medium" },
          { title: "Coin Change II", slug: "coin-change-ii", difficulty: "Medium" },
          { title: "Target Sum", slug: "target-sum", difficulty: "Medium" },
          { title: "Interleaving String", slug: "interleaving-string", difficulty: "Medium" },
          { title: "Longest Increasing Path in a Matrix", slug: "longest-increasing-path-in-a-matrix", difficulty: "Hard" },
          { title: "Distinct Subsequences", slug: "distinct-subsequences", difficulty: "Hard" },
          { title: "Edit Distance", slug: "edit-distance", difficulty: "Medium" },
          { title: "Burst Balloons", slug: "burst-balloons", difficulty: "Hard" },
          { title: "Regular Expression Matching", slug: "regular-expression-matching", difficulty: "Hard" },
        ],
      },
      {
        title: "Greedy",
        problems: [
          { title: "Maximum Subarray", slug: "maximum-subarray", difficulty: "Medium" },
          { title: "Jump Game", slug: "jump-game", difficulty: "Medium" },
          { title: "Jump Game II", slug: "jump-game-ii", difficulty: "Medium" },
          { title: "Gas Station", slug: "gas-station", difficulty: "Medium" },
          { title: "Hand of Straights", slug: "hand-of-straights", difficulty: "Medium" },
          { title: "Merge Triplets to Form Target Triplet", slug: "merge-triplets-to-form-target-triplet", difficulty: "Medium" },
          { title: "Partition Labels", slug: "partition-labels", difficulty: "Medium" },
          { title: "Valid Parenthesis String", slug: "valid-parenthesis-string", difficulty: "Medium" },
        ],
      },
      {
        title: "Intervals",
        problems: [
          { title: "Insert Interval", slug: "insert-interval", difficulty: "Medium" },
          { title: "Merge Intervals", slug: "merge-intervals", difficulty: "Medium" },
          { title: "Non-overlapping Intervals", slug: "non-overlapping-intervals", difficulty: "Medium" },
          { title: "Meeting Rooms", slug: "meeting-rooms", difficulty: "Easy" },
          { title: "Meeting Rooms II", slug: "meeting-rooms-ii", difficulty: "Medium" },
          { title: "Minimum Interval to Include Each Query", slug: "minimum-interval-to-include-each-query", difficulty: "Hard" },
        ],
      },
      {
        title: "Math & Geometry",
        problems: [
          { title: "Rotate Image", slug: "rotate-image", difficulty: "Medium" },
          { title: "Spiral Matrix", slug: "spiral-matrix", difficulty: "Medium" },
          { title: "Set Matrix Zeroes", slug: "set-matrix-zeroes", difficulty: "Medium" },
          { title: "Happy Number", slug: "happy-number", difficulty: "Easy" },
          { title: "Plus One", slug: "plus-one", difficulty: "Easy" },
          { title: "Pow(x, n)", slug: "powx-n", difficulty: "Medium" },
          { title: "Multiply Strings", slug: "multiply-strings", difficulty: "Medium" },
          { title: "Detect Squares", slug: "detect-squares", difficulty: "Medium" },
        ],
      },
      {
        title: "Bit Manipulation",
        problems: [
          { title: "Single Number", slug: "single-number", difficulty: "Easy" },
          { title: "Number of 1 Bits", slug: "number-of-1-bits", difficulty: "Easy" },
          { title: "Counting Bits", slug: "counting-bits", difficulty: "Easy" },
          { title: "Reverse Bits", slug: "reverse-bits", difficulty: "Easy" },
          { title: "Missing Number", slug: "missing-number", difficulty: "Easy" },
          { title: "Sum of Two Integers", slug: "sum-of-two-integers", difficulty: "Medium" },
          { title: "Reverse Integer", slug: "reverse-integer", difficulty: "Medium" },
        ],
      },
    ],
  },
  {
    id: "neetcode-250",
    name: "NeetCode 250",
    shortName: "NC 250",
    description:
      "An expanded 250-problem list building on NeetCode 150, adding deeper coverage of advanced patterns and edge cases for senior-level interview preparation.",
    totalProblems: 250,
    groups: [
      {
        title: "Arrays & Hashing",
        problems: [
          { title: "Contains Duplicate", slug: "contains-duplicate", difficulty: "Easy" },
          { title: "Valid Anagram", slug: "valid-anagram", difficulty: "Easy" },
          { title: "Two Sum", slug: "two-sum", difficulty: "Easy" },
          { title: "Group Anagrams", slug: "group-anagrams", difficulty: "Medium" },
          { title: "Top K Frequent Elements", slug: "top-k-frequent-elements", difficulty: "Medium" },
          { title: "Encode and Decode Strings", slug: "encode-and-decode-strings", difficulty: "Medium" },
          { title: "Product of Array Except Self", slug: "product-of-array-except-self", difficulty: "Medium" },
          { title: "Valid Sudoku", slug: "valid-sudoku", difficulty: "Medium" },
          { title: "Longest Consecutive Sequence", slug: "longest-consecutive-sequence", difficulty: "Medium" },
          { title: "Sort Colors", slug: "sort-colors", difficulty: "Medium" },
          { title: "Find All Anagrams in a String", slug: "find-all-anagrams-in-a-string", difficulty: "Medium" },
          { title: "Majority Element", slug: "majority-element", difficulty: "Easy" },
          { title: "Missing Number", slug: "missing-number", difficulty: "Easy" },
          { title: "Find All Numbers Disappeared in an Array", slug: "find-all-numbers-disappeared-in-an-array", difficulty: "Easy" },
        ],
      },
      {
        title: "Two Pointers",
        problems: [
          { title: "Valid Palindrome", slug: "valid-palindrome", difficulty: "Easy" },
          { title: "Two Sum II - Input Array Is Sorted", slug: "two-sum-ii-input-array-is-sorted", difficulty: "Medium" },
          { title: "3Sum", slug: "3sum", difficulty: "Medium" },
          { title: "Container With Most Water", slug: "container-with-most-water", difficulty: "Medium" },
          { title: "Trapping Rain Water", slug: "trapping-rain-water", difficulty: "Hard" },
          { title: "4Sum", slug: "4sum", difficulty: "Medium" },
          { title: "3Sum Closest", slug: "3sum-closest", difficulty: "Medium" },
        ],
      },
      {
        title: "Sliding Window",
        problems: [
          { title: "Best Time to Buy and Sell Stock", slug: "best-time-to-buy-and-sell-stock", difficulty: "Easy" },
          { title: "Longest Substring Without Repeating Characters", slug: "longest-substring-without-repeating-characters", difficulty: "Medium" },
          { title: "Longest Repeating Character Replacement", slug: "longest-repeating-character-replacement", difficulty: "Medium" },
          { title: "Permutation in String", slug: "permutation-in-string", difficulty: "Medium" },
          { title: "Minimum Window Substring", slug: "minimum-window-substring", difficulty: "Hard" },
          { title: "Sliding Window Maximum", slug: "sliding-window-maximum", difficulty: "Hard" },
          { title: "Minimum Size Subarray Sum", slug: "minimum-size-subarray-sum", difficulty: "Medium" },
          { title: "Fruit Into Baskets", slug: "fruit-into-baskets", difficulty: "Medium" },
        ],
      },
      {
        title: "Stack",
        problems: [
          { title: "Valid Parentheses", slug: "valid-parentheses", difficulty: "Easy" },
          { title: "Min Stack", slug: "min-stack", difficulty: "Medium" },
          { title: "Evaluate Reverse Polish Notation", slug: "evaluate-reverse-polish-notation", difficulty: "Medium" },
          { title: "Generate Parentheses", slug: "generate-parentheses", difficulty: "Medium" },
          { title: "Daily Temperatures", slug: "daily-temperatures", difficulty: "Medium" },
          { title: "Car Fleet", slug: "car-fleet", difficulty: "Medium" },
          { title: "Largest Rectangle in Histogram", slug: "largest-rectangle-in-histogram", difficulty: "Hard" },
          { title: "Next Greater Element I", slug: "next-greater-element-i", difficulty: "Easy" },
          { title: "Asteroid Collision", slug: "asteroid-collision", difficulty: "Medium" },
        ],
      },
      {
        title: "Binary Search",
        problems: [
          { title: "Binary Search", slug: "binary-search", difficulty: "Easy" },
          { title: "Search a 2D Matrix", slug: "search-a-2d-matrix", difficulty: "Medium" },
          { title: "Koko Eating Bananas", slug: "koko-eating-bananas", difficulty: "Medium" },
          { title: "Find Minimum in Rotated Sorted Array", slug: "find-minimum-in-rotated-sorted-array", difficulty: "Medium" },
          { title: "Search in Rotated Sorted Array", slug: "search-in-rotated-sorted-array", difficulty: "Medium" },
          { title: "Time Based Key-Value Store", slug: "time-based-key-value-store", difficulty: "Medium" },
          { title: "Median of Two Sorted Arrays", slug: "median-of-two-sorted-arrays", difficulty: "Hard" },
          { title: "Find Peak Element", slug: "find-peak-element", difficulty: "Medium" },
          { title: "Search a 2D Matrix II", slug: "search-a-2d-matrix-ii", difficulty: "Medium" },
        ],
      },
      {
        title: "Linked List",
        problems: [
          { title: "Reverse Linked List", slug: "reverse-linked-list", difficulty: "Easy" },
          { title: "Merge Two Sorted Lists", slug: "merge-two-sorted-lists", difficulty: "Easy" },
          { title: "Reorder List", slug: "reorder-list", difficulty: "Medium" },
          { title: "Remove Nth Node From End of List", slug: "remove-nth-node-from-end-of-list", difficulty: "Medium" },
          { title: "Copy List with Random Pointer", slug: "copy-list-with-random-pointer", difficulty: "Medium" },
          { title: "Add Two Numbers", slug: "add-two-numbers", difficulty: "Medium" },
          { title: "Linked List Cycle", slug: "linked-list-cycle", difficulty: "Easy" },
          { title: "Find the Duplicate Number", slug: "find-the-duplicate-number", difficulty: "Medium" },
          { title: "LRU Cache", slug: "lru-cache", difficulty: "Medium" },
          { title: "Merge K Sorted Lists", slug: "merge-k-sorted-lists", difficulty: "Hard" },
          { title: "Reverse Nodes in k-Group", slug: "reverse-nodes-in-k-group", difficulty: "Hard" },
          { title: "Intersection of Two Linked Lists", slug: "intersection-of-two-linked-lists", difficulty: "Easy" },
          { title: "Palindrome Linked List", slug: "palindrome-linked-list", difficulty: "Easy" },
        ],
      },
      {
        title: "Trees",
        problems: [
          { title: "Invert Binary Tree", slug: "invert-binary-tree", difficulty: "Easy" },
          { title: "Maximum Depth of Binary Tree", slug: "maximum-depth-of-binary-tree", difficulty: "Easy" },
          { title: "Diameter of Binary Tree", slug: "diameter-of-binary-tree", difficulty: "Easy" },
          { title: "Balanced Binary Tree", slug: "balanced-binary-tree", difficulty: "Easy" },
          { title: "Same Tree", slug: "same-tree", difficulty: "Easy" },
          { title: "Subtree of Another Tree", slug: "subtree-of-another-tree", difficulty: "Easy" },
          { title: "Lowest Common Ancestor of a BST", slug: "lowest-common-ancestor-of-a-binary-search-tree", difficulty: "Medium" },
          { title: "Binary Tree Level Order Traversal", slug: "binary-tree-level-order-traversal", difficulty: "Medium" },
          { title: "Binary Tree Right Side View", slug: "binary-tree-right-side-view", difficulty: "Medium" },
          { title: "Count Good Nodes in Binary Tree", slug: "count-good-nodes-in-binary-tree", difficulty: "Medium" },
          { title: "Validate Binary Search Tree", slug: "validate-binary-search-tree", difficulty: "Medium" },
          { title: "Kth Smallest Element in a BST", slug: "kth-smallest-element-in-a-bst", difficulty: "Medium" },
          { title: "Construct Binary Tree from Preorder and Inorder Traversal", slug: "construct-binary-tree-from-preorder-and-inorder-traversal", difficulty: "Medium" },
          { title: "Binary Tree Maximum Path Sum", slug: "binary-tree-maximum-path-sum", difficulty: "Hard" },
          { title: "Serialize and Deserialize Binary Tree", slug: "serialize-and-deserialize-binary-tree", difficulty: "Hard" },
          { title: "Path Sum", slug: "path-sum", difficulty: "Easy" },
          { title: "Path Sum II", slug: "path-sum-ii", difficulty: "Medium" },
          { title: "Flatten Binary Tree to Linked List", slug: "flatten-binary-tree-to-linked-list", difficulty: "Medium" },
          { title: "Populating Next Right Pointers in Each Node", slug: "populating-next-right-pointers-in-each-node", difficulty: "Medium" },
        ],
      },
      {
        title: "Tries",
        problems: [
          { title: "Implement Trie (Prefix Tree)", slug: "implement-trie-prefix-tree", difficulty: "Medium" },
          { title: "Design Add and Search Words Data Structure", slug: "design-add-and-search-words-data-structure", difficulty: "Medium" },
          { title: "Word Search II", slug: "word-search-ii", difficulty: "Hard" },
        ],
      },
      {
        title: "Heap / Priority Queue",
        problems: [
          { title: "Kth Largest Element in a Stream", slug: "kth-largest-element-in-a-stream", difficulty: "Easy" },
          { title: "Last Stone Weight", slug: "last-stone-weight", difficulty: "Easy" },
          { title: "K Closest Points to Origin", slug: "k-closest-points-to-origin", difficulty: "Medium" },
          { title: "Kth Largest Element in an Array", slug: "kth-largest-element-in-an-array", difficulty: "Medium" },
          { title: "Task Scheduler", slug: "task-scheduler", difficulty: "Medium" },
          { title: "Design Twitter", slug: "design-twitter", difficulty: "Medium" },
          { title: "Find Median from Data Stream", slug: "find-median-from-data-stream", difficulty: "Hard" },
          { title: "Top K Frequent Words", slug: "top-k-frequent-words", difficulty: "Medium" },
          { title: "Sort Characters By Frequency", slug: "sort-characters-by-frequency", difficulty: "Medium" },
        ],
      },
      {
        title: "Backtracking",
        problems: [
          { title: "Subsets", slug: "subsets", difficulty: "Medium" },
          { title: "Combination Sum", slug: "combination-sum", difficulty: "Medium" },
          { title: "Permutations", slug: "permutations", difficulty: "Medium" },
          { title: "Subsets II", slug: "subsets-ii", difficulty: "Medium" },
          { title: "Combination Sum II", slug: "combination-sum-ii", difficulty: "Medium" },
          { title: "Word Search", slug: "word-search", difficulty: "Medium" },
          { title: "Palindrome Partitioning", slug: "palindrome-partitioning", difficulty: "Medium" },
          { title: "Letter Combinations of a Phone Number", slug: "letter-combinations-of-a-phone-number", difficulty: "Medium" },
          { title: "N-Queens", slug: "n-queens", difficulty: "Hard" },
          { title: "Combinations", slug: "combinations", difficulty: "Medium" },
          { title: "Permutations II", slug: "permutations-ii", difficulty: "Medium" },
        ],
      },
      {
        title: "Graphs",
        problems: [
          { title: "Number of Islands", slug: "number-of-islands", difficulty: "Medium" },
          { title: "Clone Graph", slug: "clone-graph", difficulty: "Medium" },
          { title: "Max Area of Island", slug: "max-area-of-island", difficulty: "Medium" },
          { title: "Pacific Atlantic Water Flow", slug: "pacific-atlantic-water-flow", difficulty: "Medium" },
          { title: "Surrounded Regions", slug: "surrounded-regions", difficulty: "Medium" },
          { title: "Rotting Oranges", slug: "rotting-oranges", difficulty: "Medium" },
          { title: "Walls and Gates", slug: "walls-and-gates", difficulty: "Medium" },
          { title: "Course Schedule", slug: "course-schedule", difficulty: "Medium" },
          { title: "Course Schedule II", slug: "course-schedule-ii", difficulty: "Medium" },
          { title: "Redundant Connection", slug: "redundant-connection", difficulty: "Medium" },
          { title: "Number of Connected Components in an Undirected Graph", slug: "number-of-connected-components-in-an-undirected-graph", difficulty: "Medium" },
          { title: "Graph Valid Tree", slug: "graph-valid-tree", difficulty: "Medium" },
          { title: "Word Ladder", slug: "word-ladder", difficulty: "Hard" },
          { title: "Is Graph Bipartite?", slug: "is-graph-bipartite", difficulty: "Medium" },
          { title: "Keys and Rooms", slug: "keys-and-rooms", difficulty: "Medium" },
        ],
      },
      {
        title: "Advanced Graphs",
        problems: [
          { title: "Reconstruct Itinerary", slug: "reconstruct-itinerary", difficulty: "Hard" },
          { title: "Min Cost to Connect All Points", slug: "min-cost-to-connect-all-points", difficulty: "Medium" },
          { title: "Network Delay Time", slug: "network-delay-time", difficulty: "Medium" },
          { title: "Swim in Rising Water", slug: "swim-in-rising-water", difficulty: "Hard" },
          { title: "Alien Dictionary", slug: "alien-dictionary", difficulty: "Hard" },
          { title: "Cheapest Flights Within K Stops", slug: "find-cheapest-flights-within-k-stops", difficulty: "Medium" },
          { title: "Path with Minimum Effort", slug: "path-with-minimum-effort", difficulty: "Medium" },
        ],
      },
      {
        title: "1-D Dynamic Programming",
        problems: [
          { title: "Climbing Stairs", slug: "climbing-stairs", difficulty: "Easy" },
          { title: "Min Cost Climbing Stairs", slug: "min-cost-climbing-stairs", difficulty: "Easy" },
          { title: "House Robber", slug: "house-robber", difficulty: "Medium" },
          { title: "House Robber II", slug: "house-robber-ii", difficulty: "Medium" },
          { title: "Longest Palindromic Substring", slug: "longest-palindromic-substring", difficulty: "Medium" },
          { title: "Palindromic Substrings", slug: "palindromic-substrings", difficulty: "Medium" },
          { title: "Decode Ways", slug: "decode-ways", difficulty: "Medium" },
          { title: "Coin Change", slug: "coin-change", difficulty: "Medium" },
          { title: "Maximum Product Subarray", slug: "maximum-product-subarray", difficulty: "Medium" },
          { title: "Word Break", slug: "word-break", difficulty: "Medium" },
          { title: "Longest Increasing Subsequence", slug: "longest-increasing-subsequence", difficulty: "Medium" },
          { title: "Partition Equal Subset Sum", slug: "partition-equal-subset-sum", difficulty: "Medium" },
          { title: "Maximum Sum Circular Subarray", slug: "maximum-sum-circular-subarray", difficulty: "Medium" },
          { title: "Perfect Squares", slug: "perfect-squares", difficulty: "Medium" },
        ],
      },
      {
        title: "2-D Dynamic Programming",
        problems: [
          { title: "Unique Paths", slug: "unique-paths", difficulty: "Medium" },
          { title: "Longest Common Subsequence", slug: "longest-common-subsequence", difficulty: "Medium" },
          { title: "Best Time to Buy and Sell Stock with Cooldown", slug: "best-time-to-buy-and-sell-stock-with-cooldown", difficulty: "Medium" },
          { title: "Coin Change II", slug: "coin-change-ii", difficulty: "Medium" },
          { title: "Target Sum", slug: "target-sum", difficulty: "Medium" },
          { title: "Interleaving String", slug: "interleaving-string", difficulty: "Medium" },
          { title: "Longest Increasing Path in a Matrix", slug: "longest-increasing-path-in-a-matrix", difficulty: "Hard" },
          { title: "Distinct Subsequences", slug: "distinct-subsequences", difficulty: "Hard" },
          { title: "Edit Distance", slug: "edit-distance", difficulty: "Medium" },
          { title: "Burst Balloons", slug: "burst-balloons", difficulty: "Hard" },
          { title: "Regular Expression Matching", slug: "regular-expression-matching", difficulty: "Hard" },
          { title: "Triangle", slug: "triangle", difficulty: "Medium" },
          { title: "Minimum Path Sum", slug: "minimum-path-sum", difficulty: "Medium" },
        ],
      },
      {
        title: "Greedy",
        problems: [
          { title: "Maximum Subarray", slug: "maximum-subarray", difficulty: "Medium" },
          { title: "Jump Game", slug: "jump-game", difficulty: "Medium" },
          { title: "Jump Game II", slug: "jump-game-ii", difficulty: "Medium" },
          { title: "Gas Station", slug: "gas-station", difficulty: "Medium" },
          { title: "Hand of Straights", slug: "hand-of-straights", difficulty: "Medium" },
          { title: "Merge Triplets to Form Target Triplet", slug: "merge-triplets-to-form-target-triplet", difficulty: "Medium" },
          { title: "Partition Labels", slug: "partition-labels", difficulty: "Medium" },
          { title: "Valid Parenthesis String", slug: "valid-parenthesis-string", difficulty: "Medium" },
          { title: "Candy", slug: "candy", difficulty: "Hard" },
          { title: "Wiggle Subsequence", slug: "wiggle-subsequence", difficulty: "Medium" },
        ],
      },
      {
        title: "Intervals",
        problems: [
          { title: "Insert Interval", slug: "insert-interval", difficulty: "Medium" },
          { title: "Merge Intervals", slug: "merge-intervals", difficulty: "Medium" },
          { title: "Non-overlapping Intervals", slug: "non-overlapping-intervals", difficulty: "Medium" },
          { title: "Meeting Rooms", slug: "meeting-rooms", difficulty: "Easy" },
          { title: "Meeting Rooms II", slug: "meeting-rooms-ii", difficulty: "Medium" },
          { title: "Minimum Interval to Include Each Query", slug: "minimum-interval-to-include-each-query", difficulty: "Hard" },
        ],
      },
      {
        title: "Math & Geometry",
        problems: [
          { title: "Rotate Image", slug: "rotate-image", difficulty: "Medium" },
          { title: "Spiral Matrix", slug: "spiral-matrix", difficulty: "Medium" },
          { title: "Set Matrix Zeroes", slug: "set-matrix-zeroes", difficulty: "Medium" },
          { title: "Happy Number", slug: "happy-number", difficulty: "Easy" },
          { title: "Plus One", slug: "plus-one", difficulty: "Easy" },
          { title: "Pow(x, n)", slug: "powx-n", difficulty: "Medium" },
          { title: "Multiply Strings", slug: "multiply-strings", difficulty: "Medium" },
          { title: "Detect Squares", slug: "detect-squares", difficulty: "Medium" },
          { title: "Count Primes", slug: "count-primes", difficulty: "Medium" },
          { title: "Excel Sheet Column Number", slug: "excel-sheet-column-number", difficulty: "Easy" },
        ],
      },
      {
        title: "Bit Manipulation",
        problems: [
          { title: "Single Number", slug: "single-number", difficulty: "Easy" },
          { title: "Number of 1 Bits", slug: "number-of-1-bits", difficulty: "Easy" },
          { title: "Counting Bits", slug: "counting-bits", difficulty: "Easy" },
          { title: "Reverse Bits", slug: "reverse-bits", difficulty: "Easy" },
          { title: "Missing Number", slug: "missing-number", difficulty: "Easy" },
          { title: "Sum of Two Integers", slug: "sum-of-two-integers", difficulty: "Medium" },
          { title: "Reverse Integer", slug: "reverse-integer", difficulty: "Medium" },
          { title: "Bitwise AND of Numbers Range", slug: "bitwise-and-of-numbers-range", difficulty: "Medium" },
          { title: "Single Number II", slug: "single-number-ii", difficulty: "Medium" },
        ],
      },
    ],
  },
];

export function getRoadmapById(id: string): Roadmap | undefined {
  return ROADMAPS.find((r) => r.id === id);
}

export function getAllSlugsForRoadmap(roadmap: Roadmap): string[] {
  return roadmap.groups.flatMap((g) => g.problems.map((p) => p.slug));
}
